name: pmoa_tts_survival
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - _sysroot_linux-64_curr_repodata_hack=3
  - abseil-cpp=20220623.0
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - aws-c-auth=0.6.24
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.11
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.18
  - aws-c-http=0.7.4
  - aws-c-io=0.13.17
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.4
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.7
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - binutils_impl_linux-64=2.40
  - blas=1.0
  - blosc=1.21.5
  - boost-cpp=1.81.0
  - bwidget=1.9.16
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.14.4
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cairo=1.16.0
  - cffi=1.17.1
  - comm=0.2.2
  - curl=8.12.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=14.2.0
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gflags=2.2.2
  - gfortran_impl_linux-64=14.2.0
  - glog=0.6.0
  - graphite2=1.3.14
  - grpc-cpp=1.51.1
  - gsl=2.7.1
  - gxx_impl_linux-64=14.2.0
  - harfbuzz=6.0.0
  - hdf5=1.14.3
  - icu=70.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.15.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.3
  - libarrow=11.0.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.1
  - libgomp=14.2.0
  - libgoogle-cloud=2.7.0
  - libgrpc=1.51.1
  - libiconv=1.18
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libpng=1.6.43
  - libprotobuf=3.21.12
  - libsanitizer=14.2.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.18.0
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.2.1
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.5.0
  - orc=1.8.2
  - packaging=24.0
  - pango=1.50.14
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pixman=0.44.2
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.8
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=11.0.0
  - pycparser=2.22
  - pygments=2.15.1
  - pytables=3.9.2
  - python=3.9.18
  - python_abi=3.9
  - pyzmq=25.1.2
  - r-base=4.2.2
  - re2=2023.02.01
  - readline=8.2
  - rpy2=3.5.11
  - s2n=1.3.37
  - sed=4.8
  - setuptools=68.2.2
  - simplegeneric=0.8.1
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.31.1
  - stack_data=0.2.0
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.4
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - autograd==1.6.2
      - autograd-gamma==0.5.0
      - bleach==6.1.0
      - causalinference==0.1.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.9
      - ecos==2.0.13
      - filelock==3.13.1
      - fonttools==4.50.0
      - formulaic==1.0.1
      - fsspec==2024.3.1
      - future==1.0.0
      - h5py==3.10.0
      - hnswlib==0.8.0
      - idna==3.6
      - importlib-resources==6.3.2
      - interface-meta==1.3.0
      - jinja2==3.1.3
      - joblib==1.3.2
      - kaggle==1.6.6
      - kiwisolver==1.4.5
      - lifelines==0.28.0
      - llvmlite==0.42.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - missingpy==0.2.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - numba==0.59.1
      - numexpr==2.9.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - osqp==0.6.5
      - pandas==2.2.1
      - patsy==0.5.6
      - pillow==10.2.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-slugify==8.0.4
      - pytz==2024.1
      - qdldl==0.1.7.post0
      - requests==2.31.0
      - scikit-learn==1.3.2
      - scikit-survival==0.22.2
      - scipy==1.11.4
      - seaborn==0.13.2
      - statsmodels==0.14.1
      - sympy==1.12
      - text-unidecode==1.3
      - threadpoolctl==3.4.0
      - torch==2.2.1
      - torchvision==0.17.1
      - tqdm==4.66.2
      - triton==2.2.0
      - tzdata==2024.1
      - tzlocal==5.2
      - urllib3==2.2.1
      - webencodings==0.5.1
      - wrapt==1.16.0
      - xgboost==2.0.3
      - zipp==3.18.1
